Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
# approot: "http://localhost:3000"
  approot: "https://www.feriko.fi/example/backend"
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
